spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:/Users/rgajjar/Downloads/HotelReservationProject-Internship-java-1-5/data
    username: sa
    password: 1234
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect



